openapi: 3.2.0
info:
  version: v2.3
  title: WSO2 API Manager - Gateway Server Startup Healthcheck API
  description: 'This document specifies a **RESTful API** for WSO2 **API Manager** - Gateway.

    Please see full swagger definition of the API which is written using swagger 2.0 specification.'
  contact:
    name: WSO2
    url: https://wso2.com/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://apis.wso2.com/api/am/gateway/v2
tags:
- name: Server Startup Healthcheck
paths:
  /server-startup-healthcheck:
    get:
      summary: Health check to check if all the API are deployed during the server startup
      responses:
        200:
          description: 'OK.

            '
          content:
            text/plain:
              schema:
                type: string
                default: OK
        500:
          description: 'Internal Server Error.

            '
          content:
            text/plain:
              schema:
                type: string
                default: Internal Server Error.
      security:
      - OAuth2Security: []
      x-code-samples:
      - lang: Curl
        source: 'curl -k "https://localhost:9443/api/am/gateway/v2/server-startup-healthcheck" -H "Authorization: Basic YWRtaW46YWRtaW4="'
      tags:
      - Server Startup Healthcheck
      operationId: getServerStartupHealthcheck
      x-operation-id-source: derived
